server:
  port: 8764
  servlet:
    context-path: /customer

ribbon:
  eureka:
    enabled: false
#    指定 要调的服务路由
product-service:
  ribbon:
    listOfServers: http://localhost:8763
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false  #禁止使用负载均衡 因为只有一个消防端
  datasource:
    url: jdbc:mysql://localhost:3306/teacher?useUnicode=true&characterEncoding=UTF-8&useSSL=FALSE&serverTimezone=GMT%2b8
#    url: jdbc:mysql://192.168.8.168:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root123
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
#服务的名称
  application:
    name: customer-service

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  不能与configuration 同时存在
#  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: uuid #uuid auto input
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
